baseurl = "https://qbear.netlify.com/"
languageCode = "en-us"
title = "QBEAR"
theme = "hugo-cards"
paginate = 20

[params]
  builtBy = "QBEAR"
  defaultImage = "bear2.png"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "https://github.com/zief0002/qbear"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "QBEAR"
     link = "https://qbear.netlify.com"

[blackfriday]
  fractions = false